# Generated by Django 4.2.27 on 2026-01-27 16:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='The text content of the social media post')),
                ('image', models.ImageField(blank=True, help_text='Optional image for the post', null=True, upload_to='post_images/')),
                ('scheduled_for', models.DateTimeField(help_text='When this post should be published')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('published', 'Published')], default='draft', help_text='Current status of the post', max_length=20)),
                ('metrics', models.JSONField(blank=True, default=dict, help_text='Engagement metrics: {"likes": 0, "views": 0}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='Owner of this post', on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'ordering': ['-scheduled_for'],
            },
        ),
    ]
