# Generated by Django 4.2.27 on 2026-01-28 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_usersettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersettings',
            name='openai_api_key_encrypted',
        ),
        migrations.AddField(
            model_name='usersettings',
            name='gemini_api_key_encrypted',
            field=models.BinaryField(blank=True, help_text='Encrypted Gemini API key', null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='metrics',
            field=models.JSONField(blank=True, default=dict, help_text='Engagement metrics: {"impressions": 0, "likes": 0, "comments": 0, "clicks": 0}'),
        ),
    ]
