# Generated by Django 4.2.27 on 2026-01-28 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_rename_openai_to_gemini'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='platform',
            field=models.CharField(choices=[('twitter', 'Twitter/X'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('linkedin', 'LinkedIn'), ('tiktok', 'TikTok')], default='twitter', help_text='Target social media platform', max_length=20),
        ),
    ]
